### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by hfm** [hfm/drop_the_latte#15]
1日目につくるもの：ロゴ

https://github.com/Tacahilo/drop_the_latte/issues/7

**Comment by putchom** [comment]
![comet_logo](https://f.cloud.github.com/assets/945841/700271/01f89550-dd40-11e2-805c-1ec165fc7a6e.jpg)

ロゴです。
"o"のところは彗星を表しています。
フォントは丸みを帯びさせ、女性的なイメージをもたせました。
