### ISSUE TITLE
メール送信機能関連

### ISSUE THREAD

**Issue by ravelll** [hfm/drop_the_latte#35]
## 2日目タスク #8
- [ ] ユーザへメール情報をメール送信アクション（sendgrid）
- [ ] メールへ画像を添付して送信
## 3日目タスク #9
- [ ] メールを送るタイミング、アルゴリズムの決定
- [ ] 添付する情報の推敲（文言、画像加工、リダイレクト）

**Comment by hfm** [comment]
2日目のタスク、3日目のタスクの親Issueリンクが間違ってたので修正しました。
